# Generated by Django 4.1 on 2022-09-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='static/avatar.svg', null=True, upload_to=''),
        ),
    ]
